/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as airtableSchema from "../airtableSchema";
import type * as lib_migrations from "../lib/migrations";
import type * as linkAirtableImports from "../linkAirtableImports";
import type * as listMessages from "../listMessages";
import type * as sendMessage from "../sendMessage";
import type * as storeAirtableAttachment from "../storeAirtableAttachment";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  airtableSchema: typeof airtableSchema;
  "lib/migrations": typeof lib_migrations;
  linkAirtableImports: typeof linkAirtableImports;
  listMessages: typeof listMessages;
  sendMessage: typeof sendMessage;
  storeAirtableAttachment: typeof storeAirtableAttachment;
}>;
